//@ sourceMappingURL=main.map
// Generated by CoffeeScript 1.6.1
(function() {
  var rtrim, shuffle, tpl1, _gaq;

  tpl1 = '<div class="panel panel-default whoisPanel active">\
                    <div class="panel-heading">\
                        <h4 class="panel-title">\
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse{{index}}"  id="collapseLink{{indexLink}}">\
                                {{domain}}\
\
                            </a>\
                        </h4>\
                    </div>\
                    <div id="collapse{{id}}" class="panel-collapse collapse">\
                        <div class="panel-body">\
                            {{info}}\
                        </div>\
                    </div>\
        </div>';

  rtrim = function(str, charlist) {
    var re;
    charlist = (!charlist ? " \\s " : (charlist + "").replace(/([\[\]\(\)\.\?\/\*\{\}\+\$\^\:])/g, "\\$1"));
    re = new RegExp("[" + charlist + "]+$", "g");
    return (str + "").replace(re, "");
  };

  $.getWhoIs = function() {
    var domain, serviceUrl;
    domain = rtrim($("#input").val(), ".am") + ".am";
    serviceUrl = "https://www.amnic.net/whois/?domain=" + domain;
    $("#loader").fadeIn();
    $("#alert").hide(0);
    $("#tabWrapper").css('margin-top', '120px');
    $.ajax({
      type: "GET",
      url: serviceUrl,
      crossDomain: true,
      cache: false,
      async: false,
      success: function(data) {
        var html, index, result;
        html = $(data);
        result = html.filter("ul");
        if (result.length < 1) {
          $("#alert").show(0);
          $("#tabWrapper").css('margin-top', '160px');
        } else {
          index = Math.floor(Math.random() * 10000000);
          result = tpl1.replace('{{domain}}', domain).replace('{{info}}', result.html()).replace('{{index}}', index).replace('{{indexLink}}', index).replace('{{id}}', index);
          $("#accordionOne").prepend(result);
          $("#accordionOne .panel .panel-collapse").removeClass('in');
          $("#collapse" + index).addClass('in');
        }
        return $("#loader").fadeOut();
      }
    });
    $("#input").val(null);
    $("#refer").show();
    $(".collapse").collapse();
    return $(function() {
      return $("body").jScrollPane();
    });
  };

  _gaq = _gaq || [];

  _gaq.push(["_setAccount", "UA-46230009-1"]);

  _gaq.push(["_trackPageview"]);

  (function() {
    var ga, s;
    ga = document.createElement("script");
    ga.type = "text/javascript";
    ga.async = true;
    ga.src = "https://ssl.google-analytics.com/ga.js";
    s = document.getElementsByTagName("script")[0];
    return s.parentNode.insertBefore(ga, s);
  })();

  shuffle = function(array) {
    var currentIndex, randomIndex, temporaryValue;
    currentIndex = array.length;
    temporaryValue = void 0;
    randomIndex = void 0;
    while (0 !== currentIndex) {
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex -= 1;
      temporaryValue = array[currentIndex];
      array[currentIndex] = array[randomIndex];
      array[randomIndex] = temporaryValue;
    }
    return array;
  };

  jQuery(function($) {
    $(function() {
      var i, topDomains, _results;
      $("body").jScrollPane();
      topDomains = shuffle(window.topDomains);
      i = 0;
      _results = [];
      while (i < 9) {
        $("#accordionTwo").prepend("<div class='panel panel-default whoisPanel active'><div class='panel-heading'><h4 class='panel-title'><a target='_blank' href='http://" + topDomains[i].url + "'>" + topDomains[i].url.toUpperCase() + "</a> <span class='info'><a target='_blank' href='mailto:" + topDomains[i].email + "?subject=Buy+domain+with+(AMWEBWhoIs)&body=Hi,+i+am+requsting+price+for:+" + topDomains[i].url.toUpperCase() + "'>Request Price</a></span></h4></div></div>");
        _results.push(i++);
      }
      return _results;
    });
    $("#get").click(function(e) {
      e.preventDefault();
      return $.getWhoIs();
    });
    $("#whoForm").submit(function(e) {
      e.preventDefault();
      return $.getWhoIs();
    });
    return $('#myTab a').click(function(e) {
      e.preventDefault();
      return $(this).tab('show');
    });
  });

}).call(this);
